sequenceDiagram
  participant Broker
  participant PMR as PoaManager
  participant POA as PoaToken

  Note over Broker,POA: Precondition: Broker has been added to PoaManager
  Note over Broker,POA: Precondition: Broker is in active status

  alt Broker lists a new POA
    Broker->>+PMR: addToken(...)
  end

  Note over Broker,POA: PoaToken is successfully funded and Custodian activates the contract

  alt Broker claims the ETH from successful funding
    Broker->>+POA: claim()
    POA->>Broker: transfer all ETH from funding
  end
